# Import libs and modules

In [352]:
import numpy as np
import matplotlib.pyplot as plt

# The method

Given a linear system of equations:

$$Ax=b$$

The coefficient matrix $A$ can be factorized into lower and upper triangular matrices:

$$A=LU$$

Where:
$$
L = \begin{bmatrix}
l_{11} & 0 & \dots & 0 \\
l_{21} & l_{22} & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots\\ 
l_{n1} & l_{n2} & \dots & l_{nn} \\
\end{bmatrix}
$$

and 

$$
U = \begin{bmatrix}
u_{11} & u_{12} & \dots & u_{1n} \\
0 & u_{22} & \dots & u_{2n} \\
\vdots & \vdots & \ddots & \vdots \\ 
0 & 0 & \dots & u_{nn} \\
\end{bmatrix}
$$

This set contains $n^{2}$ equations but $(n^{2}+n)$ variables. Therefore $n$ variables need to be predifined for a unique solution. Therefore we set the diagonal of either $L$ or $U$ to unity. The two options are known as:

The Doolittle method ()
$$l_{ii}=1; 1\le i \le n$$

The Crout Method ()
$$u_{ii}=1; 1\le i \le n$$



In [458]:
# Doolittle Method 
def LU_decompose(A):
    
    # Matrix must be nxn
    n, _ = A.shape

    upper = np.zeros((n,n))
    lower = np.zeros((n,n))

    for i in range(n):
        for k in range(i, n):
            s = 0
            for j in range(i):
                s += lower[i][j] * upper[j][k]
            upper[i][k] = A[i][k] - s
        
            
        for k in range (i, n):
            s = 0
            for m in range(i):
                s += lower[k][m] * upper[m][i]
            lower[k][i] = (A[k][i] - s) / upper[i][i]

    return lower, upper

def foward_sub(L, b):
    
    n = L.shape[0]
    y = np.zeros(n)
    
    for i in range(n):
        s = 0
        for j in range(i-1, n):
            s += L[i][j] * y[j]
        y[i] = (b[i] - s) / L[i][i]
        
    return y

def back_sub(U, y):
    
    n = U.shape[0]
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        s = 0 
        for j in range(i+1, n):
            s += U[i][j] * x[j]
        x[i]= (y[i] - s) / U[i][i]
        
    return x

In [459]:
A = np.array([[3,-1,1],[2,3,1],[3,1,-2]])
b = np.array([1,4,6])
n = A.shape[1]
print(f'For the linear system A:\n{A}\n')
print(f'and b:\n{b}\n')

L, U = LU_decompose(A)

print(f'The Lower trianglular matrix L:\n{L}\n')
print(f'The Upper trianglular matrix U:\n{U}\n')

y = foward_sub(L, b)
print(f'Using foward sub y:\n{y}\n')
x = back_sub(U, y)
print(f'Using Back sub x:\n{x}\n')

For the linear system A:
[[ 3 -1  1]
 [ 2  3  1]
 [ 3  1 -2]]

and b:
[1 4 6]

The Lower trianglular matrix L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [1.         0.54545455 1.        ]]

The Upper trianglular matrix U:
[[ 3.         -1.          1.        ]
 [ 0.          3.66666667  0.33333333]
 [ 0.          0.         -3.18181818]]

Using foward sub y:
[1.         3.33333333 4.18181818]

Using Back sub x:
[ 1.11428571  1.02857143 -1.31428571]

